name: weatherify
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get: ^4.6.6
  google_fonts: ^6.1.0
  intl: ^0.18.1
  sleek_circular_slider: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_local_notifications: ^15.1.1
  permission_handler: ^11.0.0
  flutter_launcher_icons: ^0.13.1
  


flutter_icons:
  android: true
  ios: false
  image_path: "android/app/src/main/res/drawable/flutter_logo.png"


dev_dependencies:

  
  flutter_lints: ^2.0.0



     
flutter:

  
  uses-material-design: true

 
  assets:
    - assets/


 
